version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackathonDB
    ports:
      - "5432:5432"