# Generated by Django 4.1.6 on 2023-07-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_student_id_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source',
            new_name='topic',
        ),
    ]
