# Generated by Django 4.1.6 on 2023-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_test_course_alter_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='option_1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='option_2',
            new_name='variants',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AlterField(
            model_name='test',
            name='correct',
            field=models.IntegerField(),
        ),
    ]
