# Generated by Django 4.1.6 on 2023-07-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_option_1_test_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='variants',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.IntegerField(),
        ),
    ]
